Person.create(name: "Nicolas I")
Person.create(name: "Celia")
Person.create(name: "Nicolas II", father_id: 1, mother_id: 2)
Person.create(name: "Lups")
Person.create(name: "Mawie", father_id: 3, mother_id: 4)
Person.create(name: "Hector", father_id: 3, mother_id: 4)
Person.create(name: "Cesar", father_id: 3, mother_id: 4)
Person.create(name: "Sofia", father_id: 6)
Person.create(name: "Percy", mother_id: 5)
